### PR TITLE
add Meson build; remove Makefile

### PR DESCRIPTION
**Pull request by SeanMcG**

### CODE REVIEW

**Comment by jbkempf** [comment]
Ready?

**Comment by SeanMcG** [comment]
> Ready?

I think I might have missed a compiler flag or two... let me double check.

**Comment by SeanMcG** [comment]
Should be good now.

**Comment by SeanMcG** [comment]
Ping review

**Comment by jbkempf** [comment]
It's OK for me.

@cmassiot ?

**Comment by cmassiot** [comment]
Can you explain what this PR is trying to achieve, besides removing a build system included almost everywhere that takes 80 lines of code, and adding a more confidential build system with more than 100 lines?

**Comment by SeanMcG** [comment]
No real reason -- it was fun to do. I'll close the request for now, if you change your mind let me know.

**Pull request closed without merging**
